name: Send Email
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtpout.secureserver.net
          port: 465
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Androidplay
          from: ${{secrets.MAIL_USERNAME}}
          subject: Sample report
          body: Test email
          contentType: text/plain
          to: ankushbose5@gmail.com